version: '2.3'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  application:
    build: .
    command: tail -F anything
    ports:
      - 5000:5000
    environment:
      DB_HOST: mongo
      PORT: 5000
    volumes:
      - .:/opt/app:delegated
