version: '2.3'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  application:
    build: .
    command: npm run dev
    ports:
      - 5000:$PORT
    environment:
      DB_NAME: $DB_NAME
      DB_PORT: $DB_PORT
      DB_HOST: $DB_HOST
      PORT: $PORT
    volumes:
      - .:/opt/app:delegated
